[package]
name = "loki"
version = "0.0.1"
edition = "2021"

[dependencies]
color-eyre = "0.6"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
xxhash-rust = { version = "0.8", features = ["xxh3"] }
