[package]
name = "loki"
version = "0.0.2"
edition = "2021"

[dependencies]
color-eyre = "0.6"
indoc = "2"
itertools = "0.13"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
walkdir = "2"
xxhash-rust = { version = "0.8", features = ["xxh3"] }
