[package]
name = "loki"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6"
indoc = "2.0"
itertools = "0.11"
serde = { version = "1.0", features = ["derive"] }
toml = "0.7"
walkdir = "2.3"
xxhash-rust = { version = "0.8", features = ["xxh3"] }
